apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "argo-cd"
  description: "Argo CD"
  annotations:
    github.com/project-slug: pthornton/argocd
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://localhost:3000
      title: ArgoCD
      icon: dashboard
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/guests"

