## Argo CD configuration
## Ref: https://github.com/argoproj/argo-cd
##
  
argo-cd:
  ## Server
  server:
    # -- Argo CD server name
    name: server
    # -- The number of server pods to run
    replicas: 2

  ## Argo Configs
  configs:  
    # General Argo CD configuration
    ## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cm.yaml
    cm:       
      # -- Timeout to discover if a new manifests version got published to the repository
      timeout.reconciliation: 30s
